### **Retail Revenue Intelligence System**

In [2]:
import pandas as pd
import numpy as np
from pandas.conftest import ascending

In [3]:
df =pd.read_csv("Retail Revenue Intelligence System/project 001.csv")

In [4]:
df

     order_id  order_date region     category        product  quantity   price
0           1  2023-04-17   East  Electronics         Laptop         4  951.21
1           2  2023-05-02  South     Clothing          Jeans         5  600.88
2           3  2023-03-29   West  Electronics         Laptop         3  108.98
3           4  2023-06-01  North  Electronics         Laptop         5  605.10
4           5  2023-09-15  North     Clothing          Jeans         3   30.38
..        ...         ...    ...          ...            ...       ...     ...
495       496  2023-09-14   West       Sports  Tennis Racket         3  281.47
496       497  2023-01-15   West  Electronics     Smartphone         2  895.16
497       498  2023-11-16  North         Home          Mixer         2  220.97
498       499  2023-01-12  South       Sports  Tennis Racket         1  655.15
499       500  2023-07-27   West  Electronics     Headphones         2  865.71

[500 rows x 7 columns]

**Total Revenue**
* Create a new column name Revenue
* calculate the total sales of the company

In [5]:
df['Total Revenue']=[0 for i in range(len(df))]

In [6]:
df

,order_id,order_date,region,category,product,quantity,price,Total Revenue
0,1,2023-04-17,East,Electronics,Laptop,4,951.21,0
1,2,2023-05-02,South,Clothing,Jeans,5,600.88,0
2,3,2023-03-29,West,Electronics,Laptop,3,108.98,0
3,4,2023-06-01,North,Electronics,Laptop,5,605.10,0
4,5,2023-09-15,North,Clothing,Jeans,3,30.38,0
...,...,...,...,...,...,...,...,...
495,496,2023-09-14,West,Sports,Tennis Racket,3,281.47,0
496,497,2023-01-15,West,Electronics,Smartphone,2,895.16,0
497,498,2023-11-16,North,Home,Mixer,2,220.97,0
498,499,2023-01-12,South,Sports,Tennis Racket,1,655.15,0
499,500,2023-07-27,West,Electronics,Headphones,2,865.71,0

New column Created "Total Revenue"

In [13]:
def fx(a):
    return a
df['Total Revenue']=df['quantity']*df['price'].apply(fx)

In [14]:
df

,order_id,order_date,region,category,product,quantity,price,Total Revenue
0,1,2023-04-17,East,Electronics,Laptop,4,951.21,3804.84
1,2,2023-05-02,South,Clothing,Jeans,5,600.88,3004.40
2,3,2023-03-29,West,Electronics,Laptop,3,108.98,326.94
3,4,2023-06-01,North,Electronics,Laptop,5,605.10,3025.50
4,5,2023-09-15,North,Clothing,Jeans,3,30.38,91.14
...,...,...,...,...,...,...,...,...
495,496,2023-09-14,West,Sports,Tennis Racket,3,281.47,844.41
496,497,2023-01-15,West,Electronics,Smartphone,2,895.16,1790.32
497,498,2023-11-16,North,Home,Mixer,2,220.97,441.94
498,499,2023-01-12,South,Sports,Tennis Racket,1,655.15,655.15
499,500,2023-07-27,West,Electronics,Headphones,2,865.71,1731.42

**Performance as per Region**

In [74]:
df.groupby('region')['Total Revenue'].sum()

region
East     174784.78
North    199679.07
South    192852.37
West     198638.86
Name: Total Revenue, dtype: float64

* NOrth region is doing well
* East should be focused.

#### **Product Ranking**

In [44]:
df.groupby('product')['Total Revenue'].sum().sort_values(ascending=False).head(5)

product
Smartphone       69704.81
Tennis Racket    67132.27
Gym Gloves       64602.56
Lamp             60254.10
Mixer            58705.09
Name: Total Revenue, dtype: float64

Top Revenue Generator Products.

#### **Category Analysis**

we have to check our total revenue by catogery , so we can check profitable & Non- profitable Categories so we can focus on those categories

In [43]:
df.groupby('category')['Total Revenue'].sum()

category
Clothing       149675.00
Electronics    193939.04
Home           193962.53
Sports         228378.51
Name: Total Revenue, dtype: float64

* Top Profitable Category, Sports.
* Least Profitable Category ,Clothing.

#### **Time Analysis**

In [67]:
df['order_date'] = pd.to_datetime(df['order_date'])
df.groupby(df['order_date'].dt.to_period('M'))['Total Revenue'].sum().sort_values(ascending=False)

order_date
2023-08    82225.97
2023-11    76692.14
2023-06    73394.41
2023-03    70459.49
2023-10    64248.57
2023-12    63735.60
2023-05    63293.83
2023-02    61634.50
2023-09    58029.94
2023-04    55946.37
2023-01    50516.54
2023-07    45777.72
Freq: M, Name: Total Revenue, dtype: float64

* Mostly sales are in August.
* lowest sales are in July.

#### **Final Insights**

* NOrth region is doing well
* East should be focused.
* Top
Profitable
Category, Sports.
* Least
Profitable
Category, Clothing.
* Mostly
sales
are in August.
* lowest
sales
are in July.